### ISSUE TITLE
hooks don't reapply after disabling and re-enabling a mod

### ISSUE THREAD

**Issue by bananaturtlesandwich** [FujiAPI/Fuji#59] opened 2024-03-03 19:27 UTC
### Please confirm the following

- [X] I am using the latest stable/beta version of Fuji
- [X] I have confirmed that this issue is not caused by a faulty mod
- [X] I have searched and confirmed that this issue is not a duplicate

### What were you doing?

i was testing my [discord rich presence](https://github.com/FujiAPI/Fuji/files/14474290/discord.rich.presence.zip) mod and everything seems to be working well but after disabling and re-enabling the presence doesn't change when entering a new level which is set by a hook to LevelInfo.Enter 

### Your logs

```shell
no logs :p
```

**Comment by jasminegamedev** [comment] 2024-03-09 04:32
I tried reproducing this with my own test mod, and could not reproduce it on the latest version of the dev stream. It seemed like after getting re-enabled, the hook worked as expected.
Any chance you could send me your mod's source code so I can troubleshoot it better? Feel free free to send it privately on discord if you'd prefer.

**Comment by jasminegamedev** [comment] 2024-03-09 06:18
Ok, nevermind. I'm pretty sure I figured it out.
I don't think the problem was a hooks thing. I think the problem was that we weren't calling OnModUnloaded properly, which was leading to your discord rich present client not getting disposed correctly. I think I have a fix for this here:
https://github.com/FujiAPI/Fuji/commit/6e68cace8df7a270f1ef891e00f990ea4801e832
I think you may have a secondary problem though that might also be effecting it. I noticed you were calling Dispose twice, in both OnModLoaded, and the Destructor. 
```
	public override void OnModUnloaded()
	{
		client.Dispose();
	}

	~DiscordPlugin()
	{
		client.Dispose();
	}
```
I think this might fail if it gets called multiple times like that, because it becomes null after the first one from what I was seeing. So you may want to wrap these in a null check, and I don't know if you actually need the destructor one. Also might not hurt to try to dispose it if it's not null at the beginning of OnModLoaded as well, just to be safe.
I'm closing this for now, but let me know if this is still an issue after the next release, and we can reopen this.

**Closed by jasminegamedev** 2024-03-09 06:18 UTC
Labels: bug

**Comment by bananaturtlesandwich** [comment] 2024-03-09 22:15
since the client is reinitialised on mod load i don't think this is the issue

**Comment by bananaturtlesandwich** [comment] 2024-03-09 22:16
oh wait i'll check on new branch

**Comment by jasminegamedev** [comment] 2024-03-09 22:17
No, the issue was that your old client wasn't getting disposed properly I think, which I think was causing issues. I believe this should be fixed now, although it's only on dev at the moment.

**Comment by bananaturtlesandwich** [comment] 2024-03-09 22:21
dunno how to build for new branch since it needs hookgen
